Change Data for chart & export and export data processing
SiLeBAT/zoonotify-client pull request #383
Opened 2021-11-12 12:25 UTC by MicheleK17

- add translation for new data

Ticket #372

Change-Id: Ia620ba914de40617ac282370d7e2c39622d1b5d7

2021-11-14 21:08 UTC, GerberI requested changes
Commit: Refactor Table components
Good, refactored structure is now more clear and layouts are now correctly implemented.

2021-11-22 12:45 UTC, MicheleK17 commented on src/app/Main/Body/QueryPage/Services/ExportServices/StatExportServices/generateStatisticRowsCsvString.service.ts
> +                rowValues.unshift(modifyTableDataStringService(row.name));
Yes, that seemed the safer way.

2021-11-22 13:04 UTC, MicheleK17 commented on src/app/Main/Body/QueryPage/QueryPageContent/Results/TableResults/TableResults-Layout.component.tsx
> +export interface TableResultsProps {
Done.

2021-11-22 13:05 UTC, MicheleK17 commented on src/app/Main/Body/QueryPage/QueryPageContent/Results/TableResults/Table/createTableRowsWithColSum.service.tsx
> +export function createTableRowWithColSum(props: {
Done.

2021-11-22 13:05 UTC, MicheleK17 commented on src/app/Main/Body/QueryPage/QueryPageContent/Results/TableResults/Table/Table-Layout.component.tsx
> +    columnMainHeader: JSX.Element | undefined;
Done.

2021-11-22 13:05 UTC, MicheleK17 commented on src/app/Main/Body/QueryPage/QueryPageContent/Results/TableResults/TableResults-Container.component.tsx
> +            accordionHeader={accordionHeader}
Done. Last suggestion.

2021-11-22 13:05 UTC, MicheleK17 commented on src/locales/de/QueryPage.json
> +            "keine Anzeige": "keine Anzeige",
Done.

2021-11-22 14:34 UTC, GerberI approved these changes
Commit: Little changes and move center style to accordion
Looks good, thx

2021-11-22 14:41 UTC, merged