Put the shadow of the header in the foreground.
SiLeBAT/zoonotify-client pull request #393
Opened 2021-11-26 10:55 UTC by MicheleK17

Ticket: #336
Change-Id: I7d70d41fa3caf435520dbc5854234c9829c119e8

2021-11-26 11:02 UTC, GerberI requested changes
Commit: Put the shadow of the header in the foreground.
Reject: Please don't use global z-indices. Use stacking context instead: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context
So in your case you should add a z-index: 0 to parents and ensure they build an own stacking context.

2021-11-26 12:58 UTC, GerberI requested changes
Commit: Use stacking context
Not correct.
A while ago i thought about to make it mandatory for developers to add a position: relative/absolute and z-index: 0 to each components main html element. This would make it impossible to mess up the z-indices.

2021-11-26 12:58 UTC, GerberI commented on src/app/Main/Header/Header.component.tsx
> +    z-index: 0;
still global, please remove

2021-11-26 12:58 UTC, GerberI commented on src/app/Main/Header/Header.component.tsx
> +    z-index: 1;
still global please remove.
The header should not be responsible of it's z position. It is the responsibility of the parent component (some layout?) to arrange the components. See also comment in QueryPageLayout how to do that.

2021-11-26 12:58 UTC, GerberI commented on src/app/Main/Body/QueryPage/QueryPage-Layout.component.tsx
> +    z-index: 1;
Nope
This component should go like:
mainStyle is the parent and should establish a new stacking context. As documented use:
mainStyle: position: relative (also the default but it must be set to establish the stacking), z-index: 0
subHeaderStyle and queryPageStyle are your components you want to arrange in the stacking-context, so:
subHeaderStyle: z-index: 1
queryPageStyle: z-index: 0

2021-11-26 12:58 UTC, GerberI commented on src/app/Main/Body/QueryPage/QueryPage-Layout.component.tsx
> +    z-index: 0;
Nope

2022-01-26 17:26 UTC, MicheleK17 commented
Resolved on new branch "story/336_new"

2022-01-26 17:26 UTC, closed without merging