Create Deploy to QA.yml
SiLeBAT/zoonotify-client pull request #580
Opened 2023-08-29 15:12 UTC by mahtabiltarabian

Ticket: #571

2023-08-30 12:19 UTC, dptolle requested changes

2023-08-30 12:19 UTC, dptolle commented on .github/workflows/Deploy to QA.yml
> +          node-version: '14'
This should be node version 18.15.0

2023-08-30 12:19 UTC, dptolle commented on .github/workflows/Deploy to QA.yml
> +        os: [ubuntu-latest, windows-latest, macos-latest]
only needs to be linux

2023-08-30 12:19 UTC, dptolle commented on .github/workflows/Deploy to QA.yml
> +        run: npm install
This should be npm ci instead of npm install

2023-08-30 12:19 UTC, dptolle commented on .github/workflows/Deploy to QA.yml
> +        run: npm run build
This should be npm run build:qa

2023-08-30 12:19 UTC, dptolle commented on .github/workflows/Deploy to QA.yml
> +          server-dir: '/qa'     # Modify this path to the QA directory on your FTP server
server-dir should be '/'

2023-08-30 12:19 UTC, dptolle commented on .github/workflows/Deploy to QA.yml
> +          local-dir: './dist'  # Modify this path to match your build output directory
local dir ist 'public' not 'dist'

2023-08-31 14:10 UTC, closed without merging

2023-09-12 18:57 UTC, mahtabiltarabian commented
Adding artifact to workflow(please check it)