add side bar content and table for prevalence page
SiLeBAT/zoonotify-client pull request #754
Opened 2024-02-14 10:17 UTC by mahtabiltarabian

2024-02-16 10:43 UTC, dptolle requested changes

2024-02-16 14:30 UTC, mahtabiltarabian commented on src/app/prevalence/components/PrevalenceMainContent.tsx
> +            <div style={{ maxWidth: "70%" }}>
yes, I used box instead div

2024-02-19 08:26 UTC, dptolle requested changes
Looks good.  Just some minor changes needed

2024-02-19 08:26 UTC, dptolle commented on src/locales/de/PrevalencePage.json
> +  "DESELECT_ALL": "Deselecteer Alles",
Deselect: Alle abwählen

2024-02-19 08:26 UTC, dptolle commented on src/locales/de/PrevalencePage.json
> +  "SELECT_ALL": "Selecteer Alles",
Select all: alle auswählen

2024-02-19 08:26 UTC, dptolle commented on src/app/prevalence/components/SelectionContext.tsx
> +export const useSelection = (): SelectionContextData => {
PLease rename the hook to: usePrevalenceFilters, or something more specific - useSelection is too general

2024-02-19 08:26 UTC, dptolle commented on src/app/prevalence/components/PrevalenceSideContent.tsx
> +    const {
Please encapsulate all the functionality into a hook.  The PrevalenceSideContent component should then use the hook to get model values and actions (functions) which are then inserted into the jsx.

2024-02-20 09:16 UTC, dptolle approved these changes

2024-02-20 10:01 UTC, merged